@echo off
echo [CLEANUP] Removing MoviePy temp files...
del /q *TEMP_MPY* 2>nul
echo [CLEANUP] Clearing temp audio...
del /q temp_audio\*.mp3 2>nul
echo [VALIDATE] Checking current data.json against schema...
python app/parser.py --validate
pause