import json
import os


def load_metadata(json_folder):
    """
    Loads the newest JSON metadata generated by extractor
    """

    if not os.path.exists(json_folder):
        print("Metadata folder not found")
        return None

    json_files = [
        os.path.join(json_folder, f)
        for f in os.listdir(json_folder)
        if f.endswith(".json")
    ]

    if not json_files:
        print("No JSON metadata found")
        return None

    latest_json = max(json_files, key=os.path.getctime)

    print(f"Using metadata from: {os.path.basename(latest_json)}")

    with open(latest_json, "r", encoding="utf-8") as f:
        data = json.load(f)

    title = data.get("title", "Chess Event")
    description = data.get("description", "")
    hashtags = data.get("hashtags", [])
    tags = data.get("tags", [])

    hashtag_text = " ".join(hashtags)

    full_description = description + "\n\n" + hashtag_text

    return {
        "title": title,
        "description": full_description,
        "tags": tags
    }